In [12]:
#4.4.3
import numpy as np
layer_output = np.ones((5,5))
layer_output += np.arange(5)
print(layer_output)

# 50% dropout rate
layer_output *= np.random.randint(0,high=2,size=layer_output.shape)
print(layer_output)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
[[1. 2. 0. 0. 0.]
 [0. 2. 0. 4. 5.]
 [1. 0. 3. 4. 5.]
 [0. 0. 3. 4. 0.]
 [0. 2. 3. 0. 0.]]
