In [1]:
#2.3.1
import numpy as np

def relu(X):
   return np.maximum(0,X)

input = np.array([1, 1, 1, 1, 1])
W = np.array([[5,78,2,34,0],
              [6,79,3,35,1],
              [7,80,4,36,2]])

b = np.array([0.5, 0.5, 0.5,])

np.dot(W, input)
output = relu(np.dot(W, input) + b)
print(output)
output = np.maximum(np.dot(W, input) + b, 0)
print(output)
output = np.dot(W, input)
print(output)
print(input.shape)
print(W.shape)

[119.5 124.5 129.5]
[119.5 124.5 129.5]
[119 124 129]
(5,)
(3, 5)


In [14]:
#2.3.2
x = np.random.random((6,3,2,4))
print(x.shape)
print(x[1])

y = np.random.random((2,4))
print(y.shape)
print(y[1])

z = np.maximum(x,y)
print(z.shape)
print(z[1])

(6, 3, 2, 4)
[[[0.26922773 0.5571577  0.10552864 0.14529972]
  [0.85519478 0.38976463 0.78168139 0.01683833]]

 [[0.2392117  0.58854396 0.42475202 0.35821531]
  [0.69339302 0.17412345 0.83509467 0.06364545]]

 [[0.0227242  0.16425072 0.41830408 0.59086963]
  [0.01799123 0.82047735 0.85623521 0.44616332]]]
(2, 4)
[0.29449922 0.72960717 0.76279559 0.71833566]
(6, 3, 2, 4)
[[[0.81147544 0.5571577  0.14373244 0.28638223]
  [0.85519478 0.72960717 0.78168139 0.71833566]]

 [[0.81147544 0.58854396 0.42475202 0.35821531]
  [0.69339302 0.72960717 0.83509467 0.71833566]]

 [[0.81147544 0.16425072 0.41830408 0.59086963]
  [0.29449922 0.82047735 0.85623521 0.71833566]]]


In [20]:
#2.3.3
p = np.random.random((2,4))
print(p.shape)
print(p)

q = np.random.random((2,4))
print(q.shape)
print(np.transpose(q))

y = np.dot(p,np.transpose(q))
print(y.shape)
print(y)

(2, 4)
[[0.08523008 0.62845091 0.03169981 0.40049069]
 [0.72895537 0.23122785 0.33161044 0.14806672]]
(2, 4)
[[0.08564437 0.69225378]
 [0.6018142  0.45975242]
 [0.79645202 0.10236202]
 [0.66449333 0.48760233]]
(2, 2)
[[0.67688093 0.54645772]
 [0.56408829 0.71707166]]


In [28]:
#2.3.3
p = np.random.random((2))
print(p.shape)
print(p)

q = np.random.random((2))
print(q.shape)
print((q))

y = np.dot(p,(q))
print(y.shape)
print(y)

(2,)
[0.75401171 0.35014453]
(2,)
[0.66273333 0.62646466]
()
0.7190618675394861


In [38]:
#2.3.4
x = np.array([[0.,1.],[2.,3.],[4.,5.]])
print(x)
print(x.shape)

y = x.reshape([1,6])
print(y)
print(y.shape)

z = np.transpose(x)
print(z)
print(z.shape)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
(3, 2)
[[0. 1. 2. 3. 4. 5.]]
(1, 6)
[[0. 2. 4.]
 [1. 3. 5.]]
(2, 3)
